apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: java-web-service
  namespace: accelerator-system
spec:
  git:
    url: https://github.com/GuyBalmas/tanzu-application-accelerator.git
    ref:
      branch: main