apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Fragment
metadata:
  name: java-rewrite-package-fragment
  namespace: accelerator-system
spec:
  displayName: Rewrite Java application's pakage name and move source files under new package path.
  git:
    url: https://github.com/GuyBalmas/tanzu-application-accelerator.git
    subPath: fragments/java-rewrite-package
    ref:
      branch: main