apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Fragment
metadata:
  name: java-rename-app-fragment
  namespace: accelerator-system
spec:
  displayName: Enables Live Update & Live Debug features
  git:
    url: https://github.com/GuyBalmas/tanzu-application-accelerator.git
    subPath: fragments/java-rename-app