apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Fragment
metadata:
  name: jvm-version-fragment
  namespace: accelerator-system
spec:
  displayName: Select Java Virtual Machine Version
  git:
    url: https://github.com/GuyBalmas/tanzu-application-accelerator.git
    subPath: fragments/jvm-version