#@ load("@ytt:data", "data")
--- 

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  #@yaml/text-templated-strings
  name: "(@= data.values.projectName @)"
  namespace: "(@= data.values.namespace @)"
  description: Tanzu Java Spring-Boot Web App, displaying kubernetes info on '/k8s' endpoint. Written by Guy Balmas.
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
    - kubernetes
  annotations:
    #@yaml/text-templated-strings
    'backstage.io/kubernetes-label-selector': "app.kubernetes.io/part-of=(@= data.values.projectName @)"
    'backstage.io/techdocs-ref': 'dir:.'
  links:
    #@yaml/text-templated-strings
    - url: "http://(@= data.values.projectName @).(@= data.values.namespace @).tap-guy-lab-p8m8nm3rts18.ts-cna.com"
      name: Hello-World
    #@yaml/text-templated-strings
    - url: "http://(@= data.values.projectName @).(@= data.values.namespace @).tap-guy-lab-p8m8nm3rts18.ts-cna.com/k8s"
      name: K8S-spec
spec:
  type: service
  lifecycle: experimental
  owner: cloud-native-applications-team
